const _default = {save: true, pipe: false};

const EVS = {

    // basic
    Commander: {pipe: true},
    Loadout: {pipe: true},
    Status: {pipe: true},

    // discovery
    DiscoveryScan: {pipe: true},
    Scan: {pipe: true},

    // travel
    SupercruiseEntry: {pipe: true},
    SupercruiseExit: {pipe: true},
    FSDJump: {pipe: true},
    ApproachBody: {pipe: true},
    LeaveBody: {pipe: true},
    Location: {pipe: true},
    StartJump: {pipe: true},
    Docked: {pipe: true},
    Undocked: {pipe: true},
    Touchdown: {pipe: true},
    Liftoff: {pipe: true},
    LaunchSRV: {pipe: true},
    DockSRV: {pipe: true},
    LaunchFighter: {pipe: true},
    DockFighter: {pipe: true},

    CrewFire: {},
    SellShipOnRebuy: {},
    CommunityGoalDiscard: {},
    SRVDestroyed: {},
    Died: {},
    AfmuRepairs: {},
    ApproachSettlement: {},
    Bounty: {},
    BuyAmmo: {},
    BuyDrones: {},
    BuyExplorationData: {},
    BuyTradeData: {},
    Cargo: {},
    ChangeCrewRole: {},
    CockpitBreached: {},
    CollectCargo: {},
    CommitCrime: {},
    CommunityGoal: {},
    CommunityGoalJoin: {},
    CrewMemberJoins: {},
    CrewMemberQuits: {},
    CrewMemberRoleChange: {},
    DataScanned: {},
    DatalinkScan: {},
    DatalinkVoucher: {},
    DockingCancelled: {},
    DockingDenied: {},
    DockingGranted: {},
    DockingRequested: {},
    EjectCargo: {},
    EndCrewSession: {},
    EngineerApply: {},
    EngineerContribution: {},
    EngineerCraft: {},
    EngineerProgress: {},
    EscapeInterdiction: {},
    FactionKillBond: {},
    FetchRemoteModule: {},
    Fileheader: {},
    Friends: {},
    FuelScoop: {},
    HeatDamage: {},
    HeatWarning: {},
    HullDamage: {},
    Interdicted: {},
    Interdiction: {},
    JetConeBoost: {},
    JoinACrew: {},
    LaunchDrone: {},
    LoadGame: {},
    Market: {},
    MarketBuy: {},
    MarketSell: {},
    MaterialCollected: {},
    MaterialDiscarded: {},
    MaterialDiscovered: {},
    MaterialTrade: {},
    Materials: {},
    MiningRefined: {},
    MissionAbandoned: {},
    MissionAccepted: {},
    MissionCompleted: {},
    MissionFailed: {},
    MissionRedirected: {},
    Missions: {},
    ModuleBuy: {},
    ModuleInfo: {},
    ModuleRetrieve: {},
    ModuleSell: {},
    ModuleSellRemote: {},
    ModuleStore: {},
    ModuleSwap: {},
    NavBeaconScan: {},
    NewCommander: {},
    Outfitting: {},
    PVPKill: {},
    Passengers: {},
    PayFines: {},
    PayLegacyFines: {},
    PowerplayCollect: {},
    PowerplayJoin: {},
    PowerplayLeave: {},
    Progress: {},
    Promotion: {},
    QuitACrew: {},
    Rank: {},
    RebootRepair: {},
    ReceiveText: {},
    RedeemVoucher: {},
    RefuelAll: {},
    Repair: {},
    RepairAll: {},
    RepairDrone: {},
    Reputation: {},
    RestockVehicle: {},
    Resurrect: {},
    Scanned: {},
    Screenshot: {},
    SearchAndRescue: {},
    SelfDestruct: {},
    SellDrones: {},
    SellExplorationData: {},
    SendText: {},
    SetUserShipName: {},
    ShieldState: {},
    ShipTargeted: {},
    Shipyard: {},
    ShipyardBuy: {},
    ShipyardNew: {},
    ShipyardSell: {},
    ShipyardSwap: {},
    ShipyardTransfer: {},
    Shutdown: {},
    Statistics: {},
    StoredModules: {},
    StoredShips: {},
    Synthesis: {},
    SystemsShutdown: {},
    TechnologyBroker: {},
    USSDrop: {},
    UnderAttack: {},
    VehicleSwitch: {},
    WingAdd: {},
    WingInvite: {},
    WingJoin: {},
    WingLeave: {},
    KickCrewMember: {},
    WingUpdate: {},
    CrewHire: {},
    CargoDepot: {},
};

for (let i in EVS) {
    if (typeof EVS[i].save === 'undefined') EVS[i].save = _default.save;
    if (typeof EVS[i].pipe === 'undefined') EVS[i].pipe = _default.pipe;
}


module.exports = EVS;

let count = 0;
for (let i in EVS) {
    count++;
}
